networks:
  default:
    name: java_spring_framework_network
volumes:
  mysql-volume:
services:
  spring:
    build:
      context: spring
    container_name: spring
    volumes:
      - ./spring/java-spring-framework/target/java-spring-framework-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/java-spring-framework.war
    depends_on:
      - mysql
  httpd:
    build:
      context: httpd
    ports:
      - 80:80
    container_name: httpd
    depends_on:
      - spring
  mysql:
    build:
      context: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
      - mysql-volume:/var/lib/mysql
