networks:
  default:
    name: java_spring_framework_network
services:
  spring:
    build:
      context: spring
    container_name: spring
  httpd:
    build:
      context: httpd
    ports:
      - 80:80
    container_name: httpd
    depends_on:
      - spring
